### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Magicgigi** [matthewpurri/Teaching-Cameras-to-Feel#3]
Hi @matthewpurri, I'm interested in this work.Your work is of great help to me. And I would like to know when the dataset and source code will be made public?
Thank you!

**Comment by matthewpurri** [comment]
Sorry for the wait, version 1.0 of the dataset has been made available for download here: https://drive.google.com/file/d/1cjrQo2S5RwP0wLOjvY4KNomGaQ8ohgwj/view?usp=sharing

I am working on creating some data exploration notebooks to get people started.
